apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    3scale.component: apicast
    3scale.component-element: staging
  app: 3scale-api-management
  name: finto-apicast-staging
  namespace: 3scale
spec:
  host: finto-3scale-apicast-staging.apps.lab.example.com
  port:
    targetPort: gateway
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: apicast-staging
    weight: 100
  wildcardPolicy: None
